WholeBrain_MVPA( ...
  'debug', false, ...
  'Gtype' , 'soslasso', ...
  'filters',{'rowfilter','colfilter'},'target', 'TrueFaces',...
  'data', ...
    {'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp01.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp02.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp03.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp04.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp05.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp06.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp07.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp08.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp09.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp10.mat'},...
  'metadata', 'C:\Users\chris\Documents\soslasso\temp\metadata.mat',...
  'cvfile','C:\Users\chris\Documents\soslasso\temp\CV_schemes.mat',...
  'cvscheme', 1, 'cvholdout', 2, 'finalholdout', 1, ...
  'lambda', 10, 'alpha', 0.1, 'environment', 'chris','orientation','tlrc', ...
  'diameter', 12, 'overlap', 6, 'shape', 'cube')