WholeBrain_MVPA( ...
  'debug', false, ...
  'Gtype' , 'searchlight', ...
  'filters',{'rowfilter','colfilter'},'target', 'TrueFaces',...
  'data', '~/data/FacePlaceObject/data/mat/handmade/TR5/jlp01.mat',...
  'metadata', '~/src/soslasso/scripts/metadata.mat',...
  'cvfile','~/src/soslasso/scripts/CV_schemes.mat',...
  'cvscheme', 1, 'cvholdout', [2,3,4,5,6,7,8,9,10], 'finalholdout', 1, ...
  'environment', 'chris','orientation','tlrc')
