if exist('TESTENV', 'var')
  if ~strcmp(TESTENV,{'lab','home'})
    error('TESTENV must be set to either "lab" or "home".');
  end
else
  error('TESTENV is unset. Set to either "lab" or "home"');
end

switch TESTENV
  case 'home'
    datadir = 'C:\Users\chris\Documents\FacePlaceObject\TR5';
    scriptdir = 'C:\Users\chris\Documents\soslasso\scripts';
  case 'lab'
    datadir = '~/data/FacePlaceObject/data/mat/handmade/TR5';
    scriptdir = '~/src/soslasso/scripts';
end

WholeBrain_MVPA( ...
  'debug', false, ...
  'Gtype' , 'searchlight', ...
  'filters',{'rowfilter','colfilter'},'target', 'TrueFaces',...
  'data', fullfile(datadir, 'jlp01.mat'),...
  'metadata', fullfile(scriptdir, 'metadata.mat'),...
  'cvfile', fullfile(scriptdir, 'CV_schemes.mat'),...
  'cvscheme', 1, 'cvholdout', [2,3,4,5,6,7,8,9,10], 'finalholdout', 1, ...
  'slradius', 6, 'slTestToUse', 'accuracyOneSided_permutation','slpermutations',10,...
  'environment', 'chris','orientation','tlrc')
