WholeBrain_MVPA( ...
  'debug', false, ...
  'Gtype' , 'soslasso', ...
  'filters',{'rowfilter','colfilter'},'target', 'TrueFaces',...
  'data', ...
    {'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp01.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp02.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp03.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp04.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp05.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp06.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp07.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp08.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp09.mat',...
    'C:\Users\chris\Documents\FacePlaceObject\TR5\jlp10.mat'},...
  'metadata', 'C:\Users\chris\Documents\soslasso\scripts\metadata.mat',...
  'cvfile','C:\Users\chris\Documents\soslasso\scripts\CV_schemes.mat',...
  'cvscheme', 1, 'cvholdout', 2, 'finalholdout', 1, ...
  'lambda', [1,5,10,20,30], 'alpha', [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], 'environment', 'chris','orientation','tlrc', ...
  'diameter', 18, 'overlap', 9, 'shape', 'sphere')