if exist('TESTENV', 'var')
  if ~strcmp(TESTENV,{'lab','home'})
    error('TESTENV must be set to either "lab" or "home".');
  end
else
  error('TESTENV is unset. Set to either "lab" or "home"');
end

switch TESTENV
  case 'home'
    datadir = 'C:\Users\chris\Documents\FacePlaceObject\TR5';
    scriptdir = 'C:\Users\chris\Documents\soslasso\scripts';
  case 'lab'
    datadir = '~/data/FacePlaceObject/data/mat/handmade/TR5';
    scriptdir = '~/src/soslasso/scripts';
end

WholeBrain_MVPA( ...
  'debug', false, ...
  'Gtype' , 'soslasso', ...
  'filters',{'rowfilter','colfilter'},'target', 'TrueFaces',...
  'data', ...
    {fullfile(datadir,'jlp01.mat'),...
     fullfile(datadir,'jlp02.mat'),...
     fullfile(datadir,'jlp03.mat'),...
     fullfile(datadir,'jlp04.mat'),...
     fullfile(datadir,'jlp05.mat'),...
     fullfile(datadir,'jlp06.mat'),...
     fullfile(datadir,'jlp07.mat'),...
     fullfile(datadir,'jlp08.mat'),...
     fullfile(datadir,'jlp09.mat'),...
     fullfile(datadir,'jlp10.mat')},...
  'metadata', fullfile(scriptdir,'metadata.mat'),...
  'cvfile', fullfile(scriptdir,'CV_schemes.mat'),...
  'cvscheme', 1, 'cvholdout', [2,3], 'finalholdout', 1, ...
  'lambda', 10, 'alpha', [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], ...
  'environment', 'chris','orientation','tlrc', ...
  'diameter', 18, 'overlap', 9, 'shape', 'sphere')
