function coords_rot = rotateXYZ(coords, x, y, z)
    rx = deg2rad(x);
    ry = deg2rad(y);
    rz = deg2rad(z);

    c = cos(rx);
    s = sin(rx);
    rmx = [...
         1, 0, 0; ...
         0, c,-s;...
         0, s, c];

    c = cos(ry);
    s = sin(ry);
    rmy = [...
         c, 0, s; ...
         0, 1, 0;...
        -s, 0, c];

    c = cos(rz);
    s = sin(rz);
    rmz = [...
         c,-s, 0; ...
         s, c, 0;...
         0, 0, 1];

    coords_rot = coords*rmz*rmy*rmx;
end
